version: '3.5'

services:

  sample-app-prod:
    container_name: sample-app-prod
    build:
      context: .
      dockerfile: Dockerfile-prod
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '8084:80'